version: '2'

services:
    # Laravel application
    laravel-phpfpm:
        build: 
            context: ./docker
            dockerfile: "Dockerfile.phpfpm"
        container_name: laravel-phpfpm
        volumes:
            - ./docker/laravel:/var/www/laravel
        links:
            - laravel-database
        ports:
            - 9010:9000
        depends_on:
            - laravel-database
        environment:
            - DB_PORT=3306
            - DB_HOST=laravel-database

    # Webserver
    nginx:
        build: 
            context: ./docker
            dockerfile: Dockerfile.nginx
        container_name: laravel-nginx
        ports:
            - "80:80"
        links:
            - laravel-phpfpm
        volumes_from:
            - laravel-phpfpm
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
        restart: always

    # The Database
    laravel-database:
        image: mariadb:10.2
        container_name: laravel-database
        volumes:
            - "./docker/db:/docker-entrypoint-initdb.d"
            - "./docker/db/dbdata:/var/lib/mysql"
        environment:
            - "MYSQL_DATABASE=laravel"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=rootpassword"
        ports:
            - "3306:3306"
        restart: always
    # The phpmyadmin
    phpmyadmin:
        depends_on:
                - laravel-database
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        restart: always
        ports:
                - 3389:80
        environment:
                - "PMA_HOST=laravel-database"
                - "MYSQL_ROOT_PASSWORD=rootpassword"

    # The minio
    minio:
        image: geoincaks/lminio.minio
        container_name: argo-artifacts
        ports:
        - "9000:9000"
        #volumes:
        #  - storage:/data
        environment:
            - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
            -  "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        command: server /data                
